name: build-and-push
on:
  push:
    branches:
      - 'main'
env:
  REGISTRY: 'ghcr.io'
  IMAGE_NAME: '${{ github.repository }}'
jobs:
  build-and-push:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout:v3'

      - uses: 'docker/login-action@v2.0.0'
        with:
          registry: '${{ env.REGISTRY }}'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - uses: 'docker/build-push-action@v3.1.1'
        with:
          context: .
          push: true
          tags: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest'
